export { default } from './MatchingGame'
export { default as MatchingGame } from './MatchingGame'
export type { MatchingGameProps } from './types'
export type { Tile, TileSide, TileButtonProps } from './types'
export { MAX_PAIRS, WRONG_FLASH_MS, shuffle, pickRandom, buildTiles } from './board'
export { default as TileButton } from './TileButton'
export { default as MatchBoard } from './MatchBoard'
export { default as MatchHeader } from './MatchHeader'
export { default as MatchSummaryDialog } from './MatchSummaryDialog'
